### ISSUE TITLE
Add support for AWS CLI v2

### ISSUE THREAD

**Issue by bgauduch** [zenika-open-source/terraform-aws-cli#47]
https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html

**Comment by MarkAndersonTrocme** [comment]
@bgauduch is this project still supported? if so I can work on this PR

**Comment by bgauduch** [comment]
Hello @MarkAndersonTrocme 👋 

Yes it is, although I didn't have much time to spend on it before 😅
I will update this repo today, any contribution is more than welcome 👍 

Have a great day !

**Comment by bgauduch** [comment]
@MarkAndersonTrocme FYI update in progress here : #59

**Comment by MattBrumpton** [comment]
I don't know if this is actively being worked upon, but the following code snippet provides installation of AWS CLIv2.

# Install AWS CLI version 2
FROM debian:${DEBIAN_VERSION} as aws-cli
ARG AWS_CLI_VERSION
ARG PYTHON_MAJOR_VERSION
RUN apt-get update 
RUN apt-get install -y --no-install-recommends curl=7.74.0-1.3+deb11u7
RUN apt-get install -y --no-install-recommends ca-certificates=20210119
RUN apt-get install -y --no-install-recommends unzip=6.0-26+deb11u1
RUN apt-get install -y --no-install-recommends groff=1.22.4-6
RUN apt-get install -y --no-install-recommends gnupg=2.2.27-2+deb11u2
RUN apt-get install -y --no-install-recommends git=1:2.30.2-1+deb11u2
RUN apt-get install -y --no-install-recommends jq=1.6-2.1
WORKDIR /workspace
RUN curl --show-error --fail --output "awscliv2.zip" --remote-name "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${AWS_CLI_VERSION}.zip" 
COPY security/awscliv2.asc ./
COPY security/awscli-exe-linux-x86_64-${AWS_CLI_VERSION}.zip.sig ./awscliv2.sig
RUN gpg --import awscliv2.asc
RUN gpg --verify awscliv2.sig awscliv2.zip
RUN unzip -u awscliv2.zip
RUN ./aws/install

...and in the final image 

COPY --from=aws-cli /usr/local/bin/ /usr/local/bin/
COPY --from=aws-cli /usr/local/aws-cli /usr/local/aws-cli

**Comment by bgauduch** [comment]
Hello and thanks for your contributino @MattBrumpton !

I'm very short on time to work on this project, any PR would be more than appreciated 😉

**Comment by MattBrumpton** [comment]
@bgauduch - PR raised

**Comment by bgauduch** [comment]
Fixed by #77 , initial work by @MattBrumpton in #70, Kudos to him 🙏
