### ISSUE TITLE
Dockerfile issue

### ISSUE THREAD

**Issue by drabdrab** [zenika-open-source/terraform-aws-cli#52]
RUN apt-get install --no-install-recommends -y curl=7.74.0-1.3+b1
should update to
RUN apt-get install --no-install-recommends -y curl=7.74.0-1.3+deb11u1

**Comment by bgauduch** [comment]
Hello @drabdrab 👋 

Thanks a lot for your report and pointing out the correction 🙏 

Pull request is open and waiting for approval #53

**Comment by bgauduch** [comment]
@drabdrab correction was merged and `zenika/terraform-aws-cli:latest` image tag is available for you to test !
