### ISSUE TITLE
Image seems to be read-only

### ISSUE THREAD

**Issue by anitesh-lal** [zenika-open-source/terraform-aws-cli#75]
Hi,
I tried to use this image "zenika/terraform-aws-cli:latest" from inside a gitlab pipeline. 
When I did a `terraform init`, it gave me a permission denied error. I tried to `mkdir .terraform && touch .terraform/testFile` without success. Hence, my suspicion that it might be a read-only filesystem.
Otherwise, it's a very useful image with just about all the tools I needed.
Thanks,
~A

**Comment by bgauduch** [comment]
Hello @anitesh-lal and thanks a lot for your interest and feedback about this container image 👍 

I personally never tried to use this image in gitlab CI, so my help about this specific use-case is very limited.

Sorry I have no solution to provide you as of now !
I will try to setup a GitlabCI pipeline to dive a bit more into the issue.

Let me now in the meantime if you succeeded to resolve this issue in the meantime 😉

**Comment by AndrewCharlesHay** [comment]
It's not read-only. I use it in Gitlab all the time without any issues. I'm not sure what your issue what be.

**Comment by bgauduch** [comment]
Hello again @anitesh-lal 👋 

I've had no issue using this image to run Gitlab Ci jobs using the documentation as seen here : https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#define-image-in-the-gitlab-ciyml-file

You might have a problem somewhere else in you pipeline configuration ?

I'm closing for now if you don't mind.
